kind: Service
apiVersion: v1
metadata:
  name: apigateway-zuul
  labels:
    deployment: apigateway-zuul
spec:
  selector:
    app: apigateway-zuul-app
  ports:
    - name: apigateway-zuul-port
      protocol: TCP
      port: 8080
      nodePort: 38080
  # 不要用type: ClusterIP，会导致没有分配nodePort（i.e. API页面查看到nodePort=0）
  #type: ClusterIP
  # 生产环境需采用type: LoadBalancer
  #type: LoadBalancer
  # 生产环境勿用！这里采用type: NodePort只是为了方便远程连接到内网Pod的Web UI上
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-zuul
  labels:
    deployment: apigateway-zuul
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway-zuul-app
  template:
    metadata:
      labels:
        app: apigateway-zuul-app
    spec:
      containers:
      - name: apigateway-zuul-container
        image: albertzheng/apigateway-zuul:0.0.4-SNAPSHOT
        env:
          - name: SPRING_BOOT_CMD_OPTS
            value: '--spring.profiles.active=prod'
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
