apiVersion: v1
kind: Service
metadata:
  name: eureka-0
spec:
  # 生产环境需采用type: LoadBalancer
  #type: LoadBalancer
  # 生产环境勿用！这里采用type: NodePort只是为了方便远程连接到内网Pod的Web UI上
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: eureka-0
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
    nodePort: 38761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-1
spec:
  #type: LoadBalancer
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: eureka-1
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
    nodePort: 38762
