server:
  port: 8100

eureka:
  client:
    # 让Eureka Client将它宿主Service的Actuator的/health端点的健康状态传播到Eureka Server.
    healthcheck:
      enabled: true

logging:
  level:
    #org.springframework.cloud: DEBUG
    #org.springframework.boot: DEBUG
    # Feign只有当logging level是DEBUG时才会按如下配置的loggerLevel来输出它处理的请求的日志信息
    #com.kyletiger.cloud.department.feign.EmployeeFeignClient: DEBUG

feign:
  hystrix:
    # 为Feign打开Hystrix支持
    enabled: true
  # 启动压缩
  compression:
    request:
      enabled: true
      # Default is 2048
      min-request-size: 2048
  client:
    config:
      employee-ms:
        # Feign loggerLevel are: none, basic, headers, full
        loggerLevel: full

management:
  security:
    # 允许Actuator的/health端点显示出详情
    enabled: false

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

flyway:
  enabled: true
  baseline-on-migrate: true
  validate-on-migrate: false
