server:
  port: 8000

spring:
  datasource:
    username: spring
    password: spring123456
    url: 'jdbc:mysql://mysql.default.svc.cluster.local:33306/employee?useLegacyDatetimeCode=false&serverTimezone=Asia/Hong_Kong&useSSL=false'

logging:
  level:
    #org.springframework.cloud: DEBUG
    #org.springframework.boot: DEBUG
    # Feign只有当logging level是DEBUG时才会按如下配置的loggerLevel来输出它处理的请求的日志信息
    com.kyletiger.cloud.employee.feign.DepartmentFeignClient: DEBUG

feign:
  hystrix:
    # 为Feign打开Hystrix支持
    enabled: true
  # 启动压缩
  compression:
    request:
      enabled: true
      # Default is 2048
      min-request-size: 2048
  client:
    config:
      employee-ms:
        # Feign loggerLevel are: none, basic, headers, full
        loggerLevel: full

management:
  #port: 8001
  security:
    # 允许Actuator的/health端点显示出详情
    enabled: false

info:
  app:
    name: employee-ms
    encoding: UTF-8
    java:
      source: 1.8.0_172
      target: 1.8.0_172

flyway:
  enabled: true
  baseline-on-migrate: true
  validate-on-migrate: false
