kind: Service
apiVersion: v1
metadata:
  name: admin-server
  labels:
    deployment: admin-server
spec:
  selector:
    app: admin-server-app
  ports:
    - name: admin-server-port
      protocol: TCP
      port: 9090
      nodePort: 39090
  # 不要用type: ClusterIP，会导致没有分配nodePort（i.e. API页面查看到nodePort=0）
  #type: ClusterIP
  # 生产环境需采用type: LoadBalancer
  #type: LoadBalancer
  # 生产环境勿用！这里采用type: NodePort只是为了方便远程连接到内网Pod的Web UI上
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  labels:
    deployment: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server-app
  template:
    metadata:
      labels:
        app: admin-server-app
    spec:
      containers:
      - name: admin-server-container
        image: albertzheng/admin-server:0.0.4-SNAPSHOT
        env:
          - name: SPRING_BOOT_CMD_OPTS
            value: '--spring.profiles.active=prod'
        ports:
        - containerPort: 9090
        imagePullPolicy: Always
