kind: Service
apiVersion: v1
metadata:
  name: config-server
  labels:
    deployment: config-server
spec:
  selector:
    app: config-server-app
  ports:
    - name: config-server-port
      protocol: TCP
      port: 8888
      nodePort: 38888
  # 不要用type: ClusterIP，会导致没有分配nodePort（i.e. API页面查看到nodePort=0）
  #type: ClusterIP
  # 生产环境需采用type: LoadBalancer
  #type: LoadBalancer
  # 生产环境勿用！这里采用type: NodePort只是为了方便远程连接到内网Pod的Web UI上
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    deployment: config-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server-app
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
      - name: config-server-container
        image: albertzheng/config-server:0.0.4-SNAPSHOT
        env:
          - name: SPRING_BOOT_CMD_OPTS
            value: '--spring.profiles.active=prod'
        ports:
        - containerPort: 8888
        imagePullPolicy: Always
